Add li cation
mosdef-hub/foyer pull request #383
Opened 2021-03-01 16:46 UTC by rmatsum836

### PR Summary:
This PR adds a SMARTS string definition for the lithium cation, `opls_406`.  Looking at the gromacs documentation, I don't see the reference for this atom type: https://github.com/gromacs/gromacs/blob/master/share/top/oplsaa.ff/atomtypes.atp#L425.  I'll try to keep looking so I can add a DOI for it.

Test files for the lithium cation have also been added into the `opls_validation` folder and `test_opls.py` has been run to add the molecule to the list of implemented OPLS molecules.  When I ran this, additional molecules were added to the txt file.  Perhaps these molecules weren't added in their respective PRs?

### PR Checklist
------------
 - [ ] Includes appropriate unit test(s)
 - [ ] Appropriate docstring(s) are added/updated
 - [ ] Code is (approximately) PEP8 compliant
 - [ ] Issue(s) raised/addressed?

2021-03-03 20:52 UTC, justinGilmer requested changes
Just a small check to confirm that these molecules are not accidentally added twice. Other than that LGTM!

2021-03-03 20:52 UTC, justinGilmer commented on foyer/tests/implemented_opls_tests.txt
>  t-butanol
Lets go through and make sure we have the correct file names for some of this. For example, `t-butanol` is listed here but in the PR there is also a `tbutanol`

2021-04-14 19:08 UTC, daico007 commented on foyer/forcefields/xml/oplsaa.xml
> +  <Type name="opls_406" class="opls_406" element="Li" mass="6.941" def="Li" desc="Li+ cation" doi=""/>
do we have a `doi` for this?

2021-04-26 16:22 UTC, daico007 approved these changes

2021-04-26 16:22 UTC, merged