Update Documentation
mosdef-hub/foyer pull request #394
Opened 2021-03-31 19:26 UTC by daico007

### PR Summary:
Update documentation removing `omnia` and `mosdef` channel. Also remove those two channels from azure yml file (except for Windows build) 

### PR Checklist
------------
 - [ ] Includes appropriate unit test(s)
 - [ ] Appropriate docstring(s) are added/updated
 - [ ] Code is (approximately) PEP8 compliant
 - [ ] Issue(s) raised/addressed?

2021-04-22 22:35 UTC, justinGilmer requested changes

2021-04-22 22:35 UTC, justinGilmer commented on docs/installation.rst
> +    $ pip install foyer
This should not be used anymore. Now that we are on conda-forge

2021-04-22 23:00 UTC, jennyfothergill commented on docs/installation.rst
> -    cd foyer
might be nice to mention how to use ymls to install dependencies here

2021-04-26 20:24 UTC, rsdefever commented
@daico007 I hate to throw away your work here, but I've also been updating this with my docs overhaul. I don't know if it makes sense to merge this PR before we merge the docs overhaul or not... :(

2021-04-26 20:28 UTC, daico007 commented
> @daico007 I hate to throw away your work here, but I've also been updating this with my docs overhaul. I don't know if it makes sense to merge this PR before we merge the docs overhaul or not... :(

That's completely fine! I did not have too much change on this PR anyway.

2021-04-26 20:28 UTC, closed without merging